version: 2
jobs:
  gcc-linux-amd64:
    docker:
      - image: gcc:8
    steps:
      - run: apt-get update; apt-get install -y --no-install-recommends libyaml-dev check
      - checkout
      - run: make test

  llvm-macos-amd64:
    macos:
      xcode: "10.0"
    steps:
      - run: brew install libyaml check
      - checkout
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - gcc-linux-amd64
      - llvm-macos-amd64
